spring:
  application:
    name: ets-provider
  profiles:
    active: dev
    include: common
  # 关系型数据库连接参数配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filters: stat
      maxActive: 50
      initialSize: 2
      maxWait: 5000
      minIdle: 10
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      maxOpenPreparedStatements: 20
      removeAbandoned: true
      removeAbandonedTimeout: 1800
      logAbandoned: true
      web-stat-filter:
        exclusions:  "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        login-username: druid
        login-password: druid

  # mongo连接基础查询配置
  data:
    mongodb:
      option:
        min-connection-per-host: 4
        max-connection-per-host: 50
      database: ets-log
      authentication-database: admin

  #redis基础参数配置
  redis:
    #    password:
    timeout: 1800000
    jedis:
      pool:
        max-active: 256
        max-idle: 64
        min-idle: 16
        max-wait: 5000ms

mybatis-plus:
  #Mapper 所对应的 XML 文件位置
  mapper-locations: classpath*:/mapper/*/*Mapper.xml,classpath*:/mapper/*Mapper.xml
  #MyBaits 别名包扫描路径，通过该属性可以给包中的类注册别名
  type-aliases-package: com.cms.ets.model.mysql.*
  configuration:
    #只对非嵌套的 resultMap 进行自动映射
    auto-mapping-behavior: partial
    #当作映射失败处理，并抛出异常和详细信息
    auto-mapping-unknown-column-behavior: failing
  #全局配置
  global-config:
    #开启自动刷新 Mapper 对应的 XML 文件；生产环境关闭
    refresh: true
    db-config:
      #数据库类型
      db-type: mysql
      #全局默认主键类型
      id-type: id_worker
      #表名前缀
      table-prefix: t_
      #逻辑已删除值
      #      logic-delete-value: 1
      #逻辑未删除值
#      logic-not-delete-value: 0
# 开启actuator
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: info, health, metrics, configprops, env, scheduledtasks
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true

#开启undertow的access-log
server:
  undertow:
    accesslog:
      enabled: true
      pattern: common
      prefix: undertow.provider.
      rotate: true
      suffix: log
  port: 54001

# dubbo的配置项值必须是字符串, 即要加双引号
dubbo:
  registry:
    address: "zookeeper://127.0.0.1:2181"
  protocol:
    name: "dubbo"
    # 开启dubbo端口自动分配功能, 将从28800开始检索
    #    port: "20890"
    accesslog: "true"
    threadpool: "cached"
    threads: "500"
    serialization: "kryo"

  provider:
    delay: "-1"
    timeout: "5000"
  consumer:
    check: "false"
    timeout: "50000"
    init: "true"
    # 关闭重试
    retries: "0"
  application:
    name: ets-provider
    # 关闭QOS特性
    qosEnable: "false"
#  monitor:
#    protocol: "registry"


---
#开发测试环境参数配置
spring:
  profiles: dev
  #mysql参数配置
  datasource:
    driverClassName: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://122.51.119.135:3306/ets?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 910212
  # mongo参数配置
  data:
    mongodb:
      uri: mongodb://root:910212@122.51.119.135:27017/
  # redis 缓存参数配置
  redis:
    host: 122.51.119.135
    port: 6379
    database: 1


---
#生产环境参数配置
spring:
  profiles: prod
  #mysql参数配置
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://122.51.119.135:3306/ets?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 910212
  # mongo参数配置
  data:
    mongodb:
      uri: mongodb://root:910212@122.51.119.135:27017/
  # redis 缓存参数配置
  redis:
    host: 122.51.119.135
    port: 6379
    database: 1
