spring:
  application:
    name: ets-provider
  profiles:
    active: dev
    include: common, datasource, mybatis, mongodb, redis, dubbo, web

server:
  port: 53002

dubbo:
  application:
    name: ets-provider
#  protocol:
#    port: 53012
#    serialization: kryo
