spring:
  application:
    name: ets-provider
  profiles:
    active: dev
    include: common, datasource, mybatis, redis, dubbo

server:
  port: 53001

dubbo:
  application:
    name: ets-provider
#  protocol:
#    port: 53011
#    serialization: kryo
