#auth-server: http://127.0.0.1:53004
spring:
  application:
    name: ets-web
  profiles:
    active: dev
    include: common
  # 使用的jackson的配置
  jackson:
    # Spring mvc的json序列化的命名为下划线模式
    #    property-naming-strategy: SNAKE_CASE
    # 时间格式
    date-format: yyyy-MM-dd HH:mm:ss
    # 时区指定为东八区
    time-zone: GMT+8
    # 过滤掉值为Null的属性
    default-property-inclusion: non_null
    generator:
      # 数字类型的属性的值也加上双引号
      WRITE_NUMBERS_AS_STRINGS: false
      WRITE_BIGDECIMAL_AS_PLAIN: false

  #redis基础参数配置
  redis:
    #    password:
    timeout: 1800000
    jedis:
      pool:
        max-active: 256
        max-idle: 64
        min-idle: 16
        max-wait: 5000ms
#  main:
#    allow-bean-definition-overriding: true
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: info, health, metrics, configprops, env, scheduledtasks
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true

#开启undertow的access-log
server:
  undertow:
    accesslog:
      enabled: true
      pattern: common
      prefix: undertow.web.
      rotate: true
      suffix: log
  port: 54002

# dubbo的配置项值必须是字符串, 即要加双引号
dubbo:
  registry:
    address: "zookeeper://127.0.0.1:2181"
  protocol:
    name: "dubbo"
    # 开启dubbo端口自动分配功能, 将从28800开始检索
    port: "20895"
    accesslog: "true"
    threadpool: "cached"
    threads: "500"
    serialization: "kryo"
  provider:
    delay: "-1"
    timeout: "5000"
  consumer:
    check: "false"
    timeout: "50000"
    init: "true"
    # 关闭重试
    retries: "0"
  application:
    name: ets-web
    # 关闭QOS特性
    qosEnable: "false"
#  monitor:
#    protocol: "registry"

---
#开发测试环境参数配置
spring:
  profiles: dev
  # redis 缓存参数配置
  redis:
    host: 106.54.164.115
    port: 6379
    database: 1
    expire: 1800


---
#生产环境参数配置
spring:
  profiles: prod
  # redis 缓存参数配置
  redis:
    host: 127.0.0.1
    port: 6379
    database: 1
    expire: 1800
