spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
#    password: linewell
    timeout: 1800000
    jedis:
      pool:
        max-active: 256
        max-idle: 64
        min-idle: 16
        max-wait: 5000ms
#   #哨兵监听redis server名称
#    sentinel:
#      master: mymaster
#    #哨兵的配置列表
#      nodes: 192.168.12.194:26379,192.168.12.194:36379,192.168.12.194:46379