spring:
  # 使用的jackson的配置
  jackson:
    # Spring mvc的json序列化的命名为下划线模式
#    property-naming-strategy: SNAKE_CASE
    # 时间格式
    date-format: yyyy-MM-dd HH:mm:ss
    # 时区指定为东八区
    time-zone: GMT+8
    # 过滤掉值为Null的属性
    default-property-inclusion: non_null
    generator:
      # 数字类型的属性的值也加上双引号
      WRITE_NUMBERS_AS_STRINGS: false
      WRITE_BIGDECIMAL_AS_PLAIN: false
  # 开启通用的freemarker设置
#  freemarker:
#    template-loader-path: classpath:/templates
#    cache: false
#    suffix: .ftl
#    charset: utf-8
#    request-context-attribute: request

# 开启actuator
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: info, health, metrics, configprops, env, scheduledtasks
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true

#开启undertow的access-log
server:
  undertow:
    accesslog:
      enabled: true
      pattern: common
      prefix: undertow.access.
      rotate: true
      suffix: log
