mybatis-plus:
  #Mapper 所对应的 XML 文件位置
  mapper-locations: classpath*:/mapper/*/*Mapper.xml,classpath*:/mapper/*Mapper.xml
  #MyBaits 别名包扫描路径，通过该属性可以给包中的类注册别名
  type-aliases-package: com.cms.ets.model.mysql.*
  configuration:
    #只对非嵌套的 resultMap 进行自动映射
    auto-mapping-behavior: partial
    #当作映射失败处理，并抛出异常和详细信息
    auto-mapping-unknown-column-behavior: failing
  #全局配置
  global-config:
    #开启自动刷新 Mapper 对应的 XML 文件；生产环境关闭
    refresh: true
    db-config:
      #数据库类型
      db-type: mysql
      #全局默认主键类型
      id-type: id_worker
      #表名前缀
      table-prefix: t_
      #逻辑已删除值
      logic-delete-value: 1
      #逻辑未删除值
      logic-not-delete-value: 0
