# dubbo的配置项值必须是字符串, 即要加双引号
dubbo:
  registry:
    address: "zookeeper://127.0.0.1:2181"
  protocol:
    name: "dubbo"
    # 开启dubbo端口自动分配功能, 将从28800开始检索
#    port: "20890"
    accesslog: "true"
    threadpool: "cached"
    threads: "500"
    serialization: "kryo"

  provider:
    delay: "-1"
    timeout: "5000"
  consumer:
    check: "false"
    timeout: "50000"
    init: "true"
    # 关闭重试
    retries: "0"
  application:
    # 关闭QOS特性
    qosEnable: "false"
#  monitor:
#    protocol: "registry"