spring:
  data:
    mongodb:
      option:
        min-connection-per-host: 10
        max-connection-per-host: 200
      database: ets-log
      authentication-database: admin


---
#开发环境参数配置
spring:
  profiles: dev
  # mongo参数配置
  data:
    mongodb:
      uri: mongodb://root:linewell@192.168.81.34:27017/
---
#测试环境参数配置
spring:
  profiles: test
  # mongo参数配置
  data:
    mongodb:
      uri: mongodb://root:linewell@192.168.81.34:27018/

---
#生产环境参数配置
spring:
  profiles: prod
  # mongo参数配置
  data:
    mongodb:
      uri: mongodb://root:linewell@192.168.81.34:27017/